apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-pulse-auth
  namespace: api-pulse
  labels:
    app.kubernetes.io/name: api-pulse
    app.kubernetes.io/part-of: odin
    odin.cd-demo.io/service: auth
spec:
  hosts:
  - '*'
  gateways:
  - api-pulse/api-pulse-gateway
  http:
  - match:
    - uri: &id001
        prefix: /auth
      headers:
        x-tenant-slug:
          exact: acme
    route:
    - destination:
        host: api-pulse-auth-latest.api-pulse.svc.cluster.local
        port:
          number: 80
    rewrite:
      uriRegexRewrite:
        match: ^/auth(/|$)(.*)
        rewrite: /\2
  - match:
    - uri: *id001
      headers:
        cookie:
          regex: (^|.*;\s*)api_pulse_tenant=acme(;|$)
    route:
    - destination:
        host: api-pulse-auth-latest.api-pulse.svc.cluster.local
        port:
          number: 80
    rewrite:
      uriRegexRewrite:
        match: ^/auth(/|$)(.*)
        rewrite: /\2
  - match:
    - uri: *id001
      headers:
        x-tenant-slug:
          exact: globex
    route:
    - destination:
        host: api-pulse-auth-latest.api-pulse.svc.cluster.local
        port:
          number: 80
    rewrite:
      uriRegexRewrite:
        match: ^/auth(/|$)(.*)
        rewrite: /\2
  - match:
    - uri: *id001
      headers:
        cookie:
          regex: (^|.*;\s*)api_pulse_tenant=globex(;|$)
    route:
    - destination:
        host: api-pulse-auth-latest.api-pulse.svc.cluster.local
        port:
          number: 80
    rewrite:
      uriRegexRewrite:
        match: ^/auth(/|$)(.*)
        rewrite: /\2
  - match:
    - uri: *id001
    route:
    - destination:
        host: api-pulse-auth-latest.api-pulse.svc.cluster.local
        port:
          number: 80
    rewrite:
      uriRegexRewrite:
        match: ^/auth(/|$)(.*)
        rewrite: /\2
