apiVersion: v1
kind: Secret
metadata:
  name: api-pulse-secrets
  namespace: api-pulse
type: Opaque
stringData:
  DB_PASSWORD: "apipulse"
  MYSQL_ROOT_PASSWORD: "root"
  JWT_SECRET: "dev-jwt-secret-change-me"
